
# Generated by CodiumAI

import pytest

class TestSetupDatabase:

    #  Creates a connection to a SQLite database named 'news.db'
    def test_creates_connection_to_database(self):
        # Arrange
        expected_db_name = 'news.db'
    
        # Act
        conn = setup_database()
    
        # Assert
        assert conn is not None
        assert conn.database == expected_db_name

    #  Creates a cursor object from the connection
    def test_creates_cursor_object(self):
        # Arrange
        conn = setup_database()
    
        # Act
        cursor = conn.cursor()
    
        # Assert
        assert cursor is not None

    #  Executes a SQL statement to create a table named 'news' with columns 'date_time', 'title', 'source', 'category', and 'url'
    def test_creates_news_table(self):
        # Arrange
        conn = setup_database()
    
        # Act
        cursor = conn.cursor()
        cursor.execute('SELECT name FROM sqlite_master WHERE type="table" AND name="news"')
        result = cursor.fetchone()
    
        # Assert
        assert result is not None

    #  'news.db' file already exists
    def test_existing_db_file(self):
        # Arrange
        expected_db_name = 'news.db'
    
        # Act
        conn = setup_database()
    
        # Assert
        assert conn is not None
        assert conn.database == expected_db_name

    #  'news' table already exists in the database
    def test_existing_news_table(self):
        # Arrange
        conn = setup_database()
    
        # Act
        cursor = conn.cursor()
        cursor.execute('SELECT name FROM sqlite_master WHERE type="table" AND name="news"')
        result = cursor.fetchone()
    
        # Assert
        assert result is not None

    #  Invalid SQL statement passed to cursor.execute()
    def test_invalid_sql_statement(self):
        # Arrange
        conn = setup_database()
    
        # Act & Assert
        with pytest.raises(sqlite3.OperationalError):
            cursor = conn.cursor()
            cursor.execute('INVALID SQL STATEMENT')
