def categorize_headline(headline):
    categories = {
        'politics': [
            'election', 'government', 'senate', 'legislation', 'diplomacy', 'congress', 'political', 'campaign',
            'democrat', 'republican', 'parliament', 'senator', 'representative', 'policy', 'voting', 'ballot',
            'candidate', 'primary', 'caucus', 'debate', 'platform', 'constituency', 'bipartisan', 'filibuster',
            'gerrymander', 'lobby', 'lobbyist', 'caucus', 'impeachment', 'referendum', 'plebiscite', 'veto',
            'legislature', 'executive', 'judiciary', 'amendment', 'bill', 'resolution', 'act', 'hearing',
            'testimony', 'subpoena', 'bloc', 'coalition', 'majority', 'minority', 'session', 'term', 'incumbent',
            'nominee', 'convention', 'delegate', 'superdelegate', 'endorsement', 'pact', 'accord', 'treaty',
            'sanction', 'embargo', 'diplomat', 'ambassador', 'consul', 'summit', 'negotiation', 'ratification',
            'sovereignty', 'statehood', 'autonomy', 'referendum', 'bureaucracy', 'administration', 'regime',
            'sanctions', 'annexation', 'apartheid', 'armistice', 'autocracy', 'cabinet', 'caucus', 'coalition',
            'communism', 'confederation', 'conservatism', 'constitution', 'democracy', 'despotism', 'dictatorship',
            'diplomacy', 'doctrine', 'dominion', 'emancipation', 'embassy', 'fascism', 'federation', 'feudalism',
            'hegemony', 'ideology', 'imperialism', 'independence', 'insurgency', 'liberalism', 'libertarianism',
            'mandate', 'marxism', 'monarchy', 'nationalism', 'oligarchy', 'opposition', 'parliamentarianism',
            'partisanship', 'plutocracy', 'populism', 'progressivism', 'proletariat', 'propaganda', 'ratify',
            'reform', 'republic', 'revolution', 'socialism', 'sovereignty', 'statecraft', 'stewardship', 'subsidy',
            'suffrage', 'totalitarianism', 'treaty', 'tribunal', 'tyranny', 'unilateralism', 'xenophobia'],
        'health': [
            'health', 'hospital', 'CDC', 'vaccine', 'disease', 'pandemic', 'epidemic', 'medical', 'medicine',
            'medical doctor', 'nurse', 'healthcare', 'FDA', 'treatment', 'patient', 'cancer', 'diabetes', 'asthma',
            'cardiovascular', 'heart disease', 'stroke', 'alzheimer', 'dementia', 'obesity', 'allergy',
            'arthritis', 'HIV', 'AIDS', 'tuberculosis', 'malaria', 'hepatitis', 'influenza', 'flu',
            'coronavirus', 'COVID-19', 'SARS', 'ebola', 'zika', 'dengue', 'cholera', 'measles', 'cystic fibrosis',
            'multiple sclerosis', 'parkinson', 'mental health', 'depression', 'anxiety', 'bipolar disorder',
            'schizophrenia', 'PTSD', 'autism', 'dermatitis', 'psoriasis', 'acne', 'infection', 'pneumonia',
            'bronchitis', 'osteoporosis', 'thyroid', 'anemia', 'lyme disease', 'food poisoning', 'appendicitis',
            'kidney stones', 'gallstones', 'hernia', 'varicose veins', 'cataracts', 'glaucoma', 'conjunctivitis',
            'myopia', 'hyperopia', 'astigmatism', 'oral health', 'gum disease', 'tooth decay', 'orthodontics',
            'root canal', 'hearing loss', 'deafness', 'tinnitus', 'ear infection', 'sinusitis', 'rhinitis',
            'laryngitis', 'tonsillitis', 'pharyngitis', 'GERD', 'ulcer', 'IBS', 'crohn’s disease', 'celiac disease',
            'lactose intolerance', 'food allergy', 'anorexia', 'bulimia', 'binge eating', 'malnutrition',
            'dehydration', 'heat stroke', 'hypothermia', 'frostbite', 'burns', 'fracture', 'sprain', 'concussion',
            'trauma', 'poisoning', 'overdose', 'withdrawal', 'addiction', 'substance abuse', 'smoking', 'alcoholism',
            'drug abuse', 'domestic violence', 'sexual assault', 'child abuse', 'elder abuse', 'self-harm',
            'suicide', 'homicide', 'accident', 'first aid', 'CPR', 'emergency', 'surgery', 'transplant',
            'chemotherapy', 'radiation therapy', 'immunotherapy', 'dialysis', 'palliative care', 'rehabilitation',
            'physical therapy', 'occupational therapy', 'speech therapy', 'audiology', 'optometry', 'podiatry',
            'chiropractic', 'acupuncture', 'massage therapy', 'yoga', 'meditation', 'naturopathy', 'homeopathy',
            'chinese medicine', 'ayurveda', 'holistic health', 'integrative medicine', 'preventive medicine',
            'sports medicine', 'pediatrics', 'geriatrics', 'obstetrics', 'gynecology', 'andrology', 'urology',
            'endocrinology', 'gastroenterology', 'pulmonology', 'cardiology', 'dermatology', 'oncology',
            'hematology', 'neurology', 'psychiatry', 'radiology', 'anesthesiology', 'ophthalmology', 'otolaryngology',
            'immunology', 'pathology', 'genetics', 'epigenetics', 'biotechnology', 'pharmacology', 'toxicology',
            'virology', 'bacteriology', 'parasitology', 'mycology', 'histology', 'cytology', 'embryology',
            'anatomy', 'physiology', 'biochemistry', 'molecular biology', 'cell biology', 'microbiology',
            'nanotechnology', 'biomedical engineering', 'bioinformatics', 'epidemiology', 'public health',
            'health policy', 'health insurance', 'medicare', 'medicaid', 'ACA', 'obamacare', 'health reform',
            'vaccine schedule', 'immunization', 'antibiotics', 'antivirals', 'antifungals', 'antiparasitics',
            'pain relief', 'analgesics', 'anesthetics', 'antidepressants', 'antipsychotics', 'mood stabilizers',
            'stimulants', 'sedatives', 'hypnotics', 'tranquilizers', 'anticonvulsants', 'antiepileptics',
            'anticoagulants', 'blood thinners', 'statins', 'ACE inhibitors', 'beta blockers', 'diuretics',
            'insulin', 'hormone therapy', 'birth control', 'contraceptives', 'fertility drugs', 'erectile dysfunction',
            'STDs', 'STIs', 'contraception', 'abortion', 'prenatal care', 'maternal health', 'childbirth',
            'labor and delivery', 'postpartum', 'neonatology', 'infant health', 'child health', 'adolescent health',
            'adult health', 'senior health', 'men’s health', 'women’s health', 'LGBTQ health', 'racial health disparities',
            'health equity', 'global health', 'health crisis', 'health emergency', 'health outbreak', 'health pandemic',
            'health epidemic', 'health scare', 'health warning', 'health alert', 'health hazard', 'health risk',
            'health threat', 'health issue', 'health problem', 'health challenge', 'health concern', 'health condition',
            'health disorder', 'health complication', 'health symptom', 'health sign', 'health test', 'health screening',
            'health checkup', 'health examination', 'health assessment', 'health diagnosis', 'health prognosis',
            'health treatment', 'health intervention', 'health care', 'health coverage', 'health plan', 'health program',
            'health campaign', 'health initiative', 'health strategy', 'health policy', 'health regulation', 'health law',
            'health guideline', 'health recommendation', 'health advice', 'health education', 'health information',
            'health communication', 'health promotion', 'health prevention', 'health protection', 'health safety',
            'health security', 'health surveillance', 'health monitoring', 'health tracking', 'health reporting',
            'health research', 'health study', 'health survey', 'health trial', 'health experiment', 'health project',
            'health grant', 'health funding', 'health investment', 'health innovation', 'health technology',
            'health data', 'health statistics', 'health analysis', 'health evidence', 'health science', 'health knowledge',
            'health expertise', 'health skill', 'health practice', 'health experience', 'health expertise',
            'health professionalism', 'health competence', 'health performance', 'health quality', 'health excellence',
            'health standard', 'health benchmark', 'health indicator', 'health metric', 'health measure', 'health outcome',
            'health impact', 'health effect', 'health benefit', 'health advantage', 'health gain', 'health improvement',
            'health progress', 'health success', 'health achievement', 'health accomplishment', 'health milestone',
            'health breakthrough', 'health discovery', 'health invention', 'health innovation', 'health advancement',
            'health evolution', 'health revolution', 'health transformation', 'health change', 'health transition',
            'health shift', 'health trend', 'health direction', 'health movement', 'health wave', 'health current',
            'health flow', 'health stream', 'health tide', 'health wind', 'health storm', 'health wave',
            'health surge', 'health flood', 'health deluge', 'health torrent', 'health avalanche', 'health landslide',
            'health eruption', 'health explosion', 'health burst', 'health outbreak', 'health epidemic', 'health pandemic',
            'health crisis', 'health emergency', 'health disaster', 'health catastrophe', 'health calamity', 'health tragedy',
            'health misfortune', 'health adversity', 'health setback', 'health difficulty', 'health obstacle', 'health barrier',
            'health hurdle', 'health challenge', 'health problem', 'health issue', 'health concern', 'health question',
            'health doubt', 'health uncertainty', 'health ambiguity', 'health complexity', 'health complication', 'health intricacy',
            'health perplexity', 'health puzzle', 'health mystery', 'health enigma', 'health riddle', 'health conundrum',
            'health dilemma', 'health quandary', 'health predicament', 'health plight', 'health distress', 'health anguish',
            'health agony', 'health pain', 'health suffering', 'health torment', 'health torture', 'health misery',
            'health sorrow', 'health grief', 'health woe', 'health heartache', 'health heartbreak', 'health sadness',
            'health depression', 'health melancholy', 'health blues', 'health despair', 'health hopelessness', 'health despondency',
            'health dejection', 'health gloom', 'health doom', 'health darkness', 'health shadow', 'health cloud',
            'health fog', 'health haze', 'health mist', 'health smog', 'health smoke', 'health dust',
            'health ash', 'health soot', 'health grime', 'health dirt', 'health filth', 'health muck',
            'health mud', 'health slime', 'health sludge', 'health ooze', 'health gunk', 'health goop',
            'health guck', 'health gloop', 'health glop', 'health gunk', 'health crud', 'health crap',
            'health junk', 'health garbage', 'health trash', 'health waste', 'health refuse', 'health rubbish',
            'health debris', 'health detritus', 'health litter', 'health scrap', 'health leftover', 'health remnant',
            'health residue', 'health sediment', 'health dregs', 'health lees', 'health grounds', 'health slag',
            'health dross', 'health chaff', 'health husk', 'health hull', 'health shell', 'health casing',
            'health covering', 'health coating', 'health layer'],
        'market': ['stocks', 'shares', 'investment', 'S&P', 'NASDAQ', 'Dow Jones', 'market', 'economy', 'trading', 'financial', 'equity', 'investor', 'bullish', 'bearish', 'portfolio'],
        'trade': ['trade', 'import', 'export', 'tariff', 'trade agreement', 'trade war', 'WTO', 'commerce', 'trading partner', 'customs', 'import duty', 'export quota', 'trade policy'],
        'war': ['war', 'conflict', 'battle', 'military action', 'armed conflict', 'warfare', 'combat', 'invasion', 'siege', 'troop', 'soldier', 'army', 'militant', 'guerrilla', 'air strike'],
        'economy': ['economy', 'GDP', 'unemployment', 'fiscal policy', 'economic', 'inflation', 'deflation', 'recession', 'growth', 'economic development', 'trade deficit', 'budget', 'finance'],
        'military': ['military', 'defense', 'armed forces', 'troops', 'army', 'navy', 'air force', 'soldier', 'militant', 'defense policy', 'veteran', 'military base', 'commander', 'officer'],
        'education': ['education', 'school', 'college', 'university', 'curriculum', 'student', 'teacher', 'educational', 'scholarship', 'academic', 'campus', 'degree', 'diploma', 'lecture'],
        'technology': ['technology', 'tech', 'AI', 'cyber', 'innovation', 'gadget', 'software', 'hardware', 'internet', 'digital', 'computing', 'IT', 'data', 'robotics', 'automation'],
        'software': ['software', 'app', 'program', 'operating system', 'application', 'developer', 'coding', 'programming', 'open source', 'SaaS', 'computing cloud'],
        'hardware': ['hardware', 'device', 'computer', 'chip', 'processor', 'gadget', 'electronics', 'PC', 'laptop', 'server', 'CPU', 'GPU', 'motherboard', 'RAM', 'storage'],
        'science': ['science', 'research', 'study', 'NASA', 'experiment', 'scientific', 'laboratory', 'discovery', 'theory', 'biology', 'chemistry', 'physics', 'astronomy', 'geology'],
        'environment': ['environment', 'climate', 'conservation', 'green energy', 'sustainability', 'pollution', 'ecology', 'wildlife', 'renewable', 'emissions', 'carbon', 'global warming', 'recycling'],
        'lifestyle': ['lifestyle', 'life', 'living', 'well-being', 'culture', 'wellness', 'fitness', 'diet', 'fashion', 'travel', 'leisure', 'hobby', 'entertainment', 'relationship'],
        'entertainment': ['entertainment', 'movie', 'TV', 'celebrity', 'music', 'film', 'series', 'actor', 'actress', 'director', 'box office', 'showbiz', 'performance', 'concert', 'festival'],
        'sports': [
            'sports', 'soccer', 'football', 'basketball', 'baseball', 'tennis', 'golf', 'olympics', 'athlete',
            'competition', 'race', 'tournament', 'world cup', 'championship', 'NBA', 'NFL', 'MLB', 'NHL', 'FIFA',
            'UEFA', 'Champions League', 'Premier League', 'La Liga', 'Bundesliga', 'Serie A', 'Ligue 1', 'MLS',
            'rugby', 'cricket', 'Formula 1', 'NASCAR', 'MMA', 'UFC', 'boxing', 'table tennis', 'badminton',
            'squash', 'hockey', 'ice hockey', 'volleyball', 'handball', 'skiing', 'snowboarding', 'surfing',
            'skateboarding', 'motorsport', 'esports', 'darts', 'billiards', 'snooker', 'bowling', 'cycling',
            'track and field', 'marathon', 'triathlon', 'gymnastics', 'figure skating', 'wrestling', 'judo',
            'taekwondo', 'karate', 'fencing', 'archery', 'biathlon', 'pentathlon', 'decathlon', 'equestrian',
            'sailing', 'rowing', 'canoeing', 'kayaking', 'diving', 'swimming', 'water polo', 'synchronized swimming',
            'aquatics', 'weightlifting', 'powerlifting', 'bodybuilding', 'crossfit', 'parkour', 'rock climbing',
            'mountaineering', 'bmx', 'mountain biking', 'road cycling', 'skating', 'rollerblading', 'indycar',
            'drag racing', 'rally', 'off-road racing', 'paddle', 'squash', 'chess', 'poker', 'bridge', 'billiards',
            'pool', 'pétanque', 'bowls', 'curling', 'bobsleigh', 'luge', 'skeleton', 'tobogganing', 'aerobics',
            'dance sport', 'cheerleading', 'baton twirling', 'kabaddi', 'sepak takraw', 'netball', 'softball',
            'lacrosse', 'polo', 'water ski', 'wakeboarding', 'kitesurfing', 'windsurfing', 'bodyboarding',
            'skimboarding', 'surf lifesaving', 'stand up paddleboarding', 'dragon boat', 'outrigger canoeing'],
        'crime': [
            'shooter', 'shooting', 'massacre', 'murder', 'homicide',
            'arson', 'theft', 'robbery', 'burglary', 'assault',
            'kidnapping', 'fraud', 'vandalism', 'drug trafficking', 'gang violence',
            'stalking', 'manslaughter', 'cybercrime', 'terrorist', 'smuggling',
            'carjacking', 'money laundering', 'domestic violence', 'corruption', 'poaching'],
        'legal': ['court', 'law', 'legal', 'judge', 'trial', 'lawyer', 'attorney', 'litigation', 'sue', 'plaintiff', 'defendant', 'verdict', 'settlement', 'justice', 'regulation'],
        'business': ['business', 'company', 'industry', 'corporate', 'enterprise', 'entrepreneur', 'startup', 'merger', 'acquisition', 'CEO', 'CFO', 'management', 'strategy', 'corporation'],
        'culture': ['culture', 'art', 'literature', 'history', 'tradition', 'heritage', 'language', 'religion', 'philosophy', 'museum', 'gallery', 'exhibition', 'cultural', 'anthropology'],
        'social': ['social', 'society', 'community', 'social media', 'networking', 'trending', 'viral', 'campaign', 'movement', 'social issue', 'activism', 'protest', 'demonstration'],
        'agriculture': ['agriculture', 'farming', 'crops', 'livestock', 'horticulture', 'aquaculture', 'agronomy','tractor', 'harvest', 'organic', 'rural'],
        'automotive': ['automotive', 'car', 'vehicle', 'motor', 'driving', 'automobile', 'truck', 'road', 'traffic','racecar', 'electric vehicle', 'EV', 'autonomous'],
        'aviation': ['aviation', 'aircraft', 'flight', 'airline', 'pilot', 'airport', 'air travel', 'jet','aeronautics', 'airplane', 'aerospace'],
        'cybersecurity': ['cybersecurity', 'hacking', 'malware', 'encryption', 'data breach', 'phishing', 'firewall','internet security', 'cyber attack', 'cyber crime'],
        'e-commerce': ['e-commerce', 'online shopping', 'e-retail', 'shopping cart', 'Amazon', 'eBay', 'e-shop','e-store', 'digital marketplace', 'online store'],
        'energy': ['energy', 'renewable', 'solar', 'wind', 'electricity', 'power', 'oil', 'gas', 'nuclear', 'battery','sustainability', 'coal', 'hydro'],
        'fashion': ['fashion', 'style', 'clothing', 'apparel', 'designer', 'runway', 'trend', 'couture', 'wardrobe','outfit', 'textile'],
        'food': ['food', 'cuisine', 'cooking', 'recipe', 'restaurant', 'chef', 'culinary', 'gourmet', 'dining','nutrition', 'organic'],
        'gaming': ['gaming', 'video game', 'esports', 'gamer', 'console', 'PC gaming', 'mobile game','game development', 'streaming', 'twitch'],
        'human rights': ['human rights', 'equality', 'justice', 'freedom', 'discrimination', 'civil rights', 'LGBTQ','racism', 'feminism', 'activism'],
        'infrastructure': ['infrastructure', 'construction', 'building', 'transport', 'urban development','public works', 'roads', 'bridges', 'utilities'],
        'insurance': ['insurance', 'policy', 'coverage', 'claim', 'premium', 'underwriting', 'actuary', 'risk','reinsurance', 'adjuster'],
        'manufacturing': ['manufacturing', 'industry', 'factory', 'production', 'machinery', 'industrial','manufacture', 'assembly', 'fabrication'],
        'mining': ['mining', 'mine', 'mineral', 'coal', 'gold', 'ore', 'drilling', 'quarry', 'excavation','resource extraction'],
        'pharmaceutical': ['pharmaceutical', 'drug', 'medicine', 'FDA', 'clinical trial', 'biotech', 'pharmacy','medication', 'vaccine'],
        'real estate': ['real estate', 'property', 'housing', 'mortgage', 'land', 'commercial', 'residential', 'realty','broker', 'agent'],
        'retail': ['retail', 'store', 'shop', 'consumer', 'sales', 'merchant', 'shopping', 'outlet', 'mall','department store'],
        'space': ['space', 'NASA', 'satellite', 'rocket', 'astronaut', 'Mars', 'moon', 'orbit', 'space station','extraterrestrial'],
        'telecommunications': ['telecommunications', 'telecom', 'phone', 'mobile', 'network', 'internet', '5G','broadband', 'wireless', 'fiber optic'],
        'tourism': ['tourism', 'travel', 'vacation', 'tourist', 'destination', 'hotel', 'resort', 'sightseeing','adventure', 'guide'],
        'transportation': ['transportation', 'transit', 'commute', 'rail', 'bus', 'subway', 'car', 'flight', 'shipping','logistics'],
        'archaeology': ['archaeology', 'excavation', 'artifact', 'temple', 'ancient', 'ruins', 'dig', 'prehistoric','archaeologist', 'heritage site', 'fossil', 'paleontology'],
        'gold market': ['gold', 'bullion', 'gold market', 'gold price', 'gold trading', 'gold mining', 'gold reserve','gold investment', 'precious metal', 'gold bar', 'gold coin'],
        'oil market': ['oil', 'crude', 'petroleum', 'oil market', 'oil price', 'oil trading', 'OPEC', 'drilling','upstream', 'downstream', 'oil rig', 'fracking', 'energy market'],
    }
    headline_lower = headline.lower()
    matched_categories = []
    for category, keywords in categories.items():
        if any(keyword in headline_lower for keyword in keywords):
            matched_categories.append(category)
    if not matched_categories:
        return 'other'
    return ', '.join(matched_categories)
